# Generated by Django 3.2.10 on 2021-12-28 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20211228_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='custom_title',
        ),
    ]
