# Generated by Django 3.2.10 on 2021-12-28 19:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20211228_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('item', wagtail.core.blocks.PageChooserBlock())], blank=True, null=True),
        ),
    ]
