# Generated by Django 3.2.10 on 2021-12-28 22:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newspage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('item', wagtail.core.blocks.PageChooserBlock()), ('description', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
