# Generated by Django 3.2.10 on 2021-12-29 01:18

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_newspage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['underline', 'bold', 'italic', 'hr'])), ('news_item', wagtail.blocks.StructBlock([('item', wagtail.blocks.PageChooserBlock()), ('description', wagtail.blocks.RichTextBlock(features=['underline', 'bold', 'italic', 'hr'], required=False))], icon='edit'))], blank=True, null=True),
        ),
    ]
