# Generated by Django 3.2.10 on 2022-07-29 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_newspage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspage',
            options={'ordering': ('date',)},
        ),
    ]
