# Generated by Django 3.2.10 on 2023-01-27 00:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_newspage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['underline', 'bold', 'italic', 'red', 'hr', 'blockquote', 'ul', 'link'])), ('news_item', wagtail.blocks.StructBlock([('item', wagtail.blocks.PageChooserBlock()), ('description', wagtail.blocks.RichTextBlock(features=['underline', 'bold', 'small', 'red', 'italic', 'blockquote', 'ul', 'hr', 'link'], required=False))], icon='edit'))], blank=True, null=True),
        ),
    ]
