# Generated by Django 3.2.7 on 2021-09-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplevelpage',
            name='updated',
            field=models.DateField(blank=True, null=True, verbose_name='Updated'),
        ),
    ]
