# Generated by Django 3.2.7 on 2021-09-06 23:47

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0003_indexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
