# Generated by Django 3.2.10 on 2022-01-03 23:20

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0007_koechellistingpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='body',
            field=wagtail.core.fields.StreamField([('year', wagtail.core.blocks.CharBlock(help_text='Year', required=True, template='streams/h2.html')), ('page', wagtail.core.blocks.RichTextBlock(features=['italic', 'link'], template='streams/page.html'))]),
        ),
    ]
