# Generated by Django 3.2.10 on 2022-02-08 17:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('top', '0008_alter_indexpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbbreviationsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('abbreviations', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(blank=True, max_length=50)), ('subheading', wagtail.core.blocks.CharBlock(blank=True, max_length=50)), ('item', wagtail.core.blocks.StructBlock([('abbreviation', wagtail.core.blocks.RichTextBlock()), ('link_id', wagtail.core.blocks.CharBlock(help_text='For making hyperlinks to this heading')), ('reference', wagtail.core.blocks.RichTextBlock())]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
