# Generated by Django 3.2.10 on 2022-02-08 17:51

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0009_abbreviationspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abbreviationspage',
            name='abbreviations',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(blank=True, form_classname='abbreviation-heading', max_length=50)), ('subheading', wagtail.blocks.CharBlock(blank=True, form_classname='abbreviation-heading', max_length=50)), ('item', wagtail.blocks.StructBlock([('abbreviation', wagtail.blocks.RichTextBlock(features=['italic', 'underline'], form_classname='abbreviation')), ('link_id', wagtail.blocks.CharBlock(help_text='For making hyperlinks to this heading')), ('reference', wagtail.blocks.RichTextBlock(features=['italic', 'underline']))], icon='edit', label='Abbreviation'))]),
        ),
    ]
