# Generated by Django 3.2.10 on 2022-02-17 22:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0015_alter_abbreviationspage_abbreviations'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplevelpage',
            name='bibliography',
            field=wagtail.core.fields.StreamField([('reference', wagtail.core.blocks.StructBlock([('reference', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'strikethrough', 'link'])), ('link_id', wagtail.core.blocks.CharBlock(help_text='For making hyperlinks to this heading'))], icon='edit', label='Reference'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abbreviationspage',
            name='abbreviations',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full-title')), ('link_id', wagtail.core.blocks.CharBlock(help_text='For making hyperlinks to this heading'))], icon='edit', label='Heading')), ('subheading', wagtail.core.blocks.StructBlock([('subheading', wagtail.core.blocks.CharBlock(max_length=100, required=False))], icon='edit', label='Subheading')), ('item', wagtail.core.blocks.StructBlock([('abbreviation', wagtail.core.blocks.RichTextBlock(features=['italic', 'underline'], form_classname='abbreviation')), ('link_id', wagtail.core.blocks.CharBlock(help_text='For making hyperlinks to this heading')), ('reference', wagtail.core.blocks.RichTextBlock(features=['italic', 'underline', 'link']))], icon='edit', label='Abbreviation'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toplevelpage',
            name='top_level_text',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full-title')), ('link_id', wagtail.core.blocks.CharBlock(help_text='For making hyperlinks to this heading'))], icon='title')), ('richtext', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'bold', 'italic', 'blockindent', 'ul', 'image', 'link', 'hr'], template='streams/richtext_block.html'))]),
        ),
    ]
