# Generated by Django 3.2.10 on 2022-04-13 22:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('top', '0016_auto_20220217_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('editors', wagtail.fields.StreamField([('editor', wagtail.blocks.StructBlock([('biography', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'bold', 'italic', 'blockindent', 'ul', 'image', 'link', 'hr'], form_classname='author'))], icon='edit', label='Editor'))])),
                ('contributors', wagtail.fields.StreamField([('contributor', wagtail.blocks.StructBlock([('biography', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'bold', 'italic', 'blockindent', 'ul', 'image', 'link', 'hr'], form_classname='author'))], icon='edit', label='Editor'))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
