# Generated by Django 3.2.10 on 2022-04-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('top', '0017_aboutpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
