# Generated by Django 3.2.10 on 2022-07-24 22:20

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0019_auto_20220715_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toplevelpage',
            name='bibliography',
            field=wagtail.fields.StreamField([('reference', wagtail.blocks.StructBlock([('reference', wagtail.blocks.RichTextBlock(features=['italic', 'bold', 'red', 'strikethrough', 'link'])), ('link_id', wagtail.blocks.CharBlock(help_text='For making hyperlinks to this heading'))], icon='edit', label='Reference'))], blank=True, null=True),
        ),
    ]
