# Generated by Django 3.2.7 on 2021-09-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20210906_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='transcription',
            field=models.TextField(),
        ),
    ]
