# Generated by Django 3.2.7 on 2021-09-06 18:28

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='credit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='first_published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='notes',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='search_term',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='translation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
