# Generated by Django 3.2.7 on 2021-09-07 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('documents', '0005_document_source_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_image',
            field=models.ForeignKey(help_text='This source image will be used at the top of the Document page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
