# Generated by Django 3.2.7 on 2021-09-07 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_source_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='source_image',
        ),
    ]
