# Generated by Django 3.2.7 on 2021-09-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20210908_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='source_link',
            new_name='repository_link',
        ),
        migrations.AddField(
            model_name='document',
            name='repository',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
