# Generated by Django 3.2.7 on 2021-09-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20210908_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
