# Generated by Django 3.2.7 on 2021-09-09 13:03

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='bibliography',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
