# Generated by Django 3.2.7 on 2021-09-09 13:21

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_document_bibliography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_title',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
