# Generated by Django 3.2.7 on 2021-09-10 23:20

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_auto_20210909_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='citation_title',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
