# Generated by Django 3.2.7 on 2021-09-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_document_citation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='citation_title',
            field=models.TextField(help_text='Field allows HTML tagging'),
        ),
    ]
