# Generated by Django 3.2.7 on 2021-09-11 16:54

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_alter_document_citation_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='document',
            name='document_title',
            field=wagtail.fields.RichTextField(blank=True, help_text='Field must be manually marked as h1'),
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=wagtail.fields.RichTextField(blank=True, help_text='Field must be manually marked as h2'),
        ),
    ]
