# Generated by Django 3.2.7 on 2021-09-11 23:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('documents', '0018_auto_20210911_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='DocumentPage',
        ),
    ]
