# Generated by Django 3.2.10 on 2021-12-17 21:21

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_auto_20211217_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpagesourcelinks',
            name='link_external',
        ),
        migrations.RemoveField(
            model_name='documentpagesourcelinks',
            name='link_text',
        ),
        migrations.AddField(
            model_name='documentpagesourcelinks',
            name='source',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Source Link'),
        ),
    ]
