# Generated by Django 3.2.10 on 2021-12-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_auto_20211217_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentpagesourcelinks',
            old_name='source',
            new_name='source_link',
        ),
    ]
