# Generated by Django 3.2.10 on 2021-12-19 23:58

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_rename_source_documentpagesourcelinks_source_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='source_link',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='DocumentPageSourceLinks',
        ),
    ]
