# Generated by Django 3.2.10 on 2021-12-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0042_alter_documentpage_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='date_precision',
            field=models.CharField(choices=[('full', 'Full'), ('month', 'Month'), ('year', 'Year')], default='full', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
