# Generated by Django 3.2.10 on 2021-12-24 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0045_auto_20211224_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpage',
            name='test_title',
        ),
    ]
