# Generated by Django 3.2.10 on 2022-01-01 19:48

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0054_alter_documentpage_commentary'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoechelNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koechel_display', models.CharField(max_length=25)),
                ('koechel_sortable', models.CharField(max_length=25)),
                ('koechel_alternate', models.CharField(blank=True, max_length=25, null=True)),
                ('koechel_title', wagtail.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KoechelNumberOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('koechel_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.koechelnumber')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='koechel_numbers', to='documents.documentpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
