# Generated by Django 3.2.10 on 2022-01-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0060_alter_documentpage_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='attachment',
            field=models.BooleanField(default=False),
        ),
    ]
