# Generated by Django 3.2.10 on 2022-02-03 18:54

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0064_remove_documentpage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='bibliography_test',
            field=wagtail.core.fields.StreamField([('reference', wagtail.core.blocks.StructBlock([('authors', wagtail.core.blocks.CharBlock(form_classname='authors')), ('reference', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'strikethrough', 'link'])), ('link_id', wagtail.core.blocks.CharBlock(help_text='For making hyperlinks to this heading'))], icon='edit', label='Reference'))], blank=True, null=True),
        ),
    ]
