# Generated by Django 3.2.10 on 2022-02-03 19:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0066_alter_documentpage_bibliography_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='bibliography_test',
            field=wagtail.core.fields.StreamField([('reference', wagtail.core.blocks.StructBlock([('reference', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'strikethrough', 'link'])), ('link_id', wagtail.core.blocks.CharBlock(help_text='For making hyperlinks to this heading'))], icon='edit', label='Reference'))], blank=True, null=True),
        ),
    ]
