# Generated by Django 3.2.10 on 2022-02-06 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0067_alter_documentpage_bibliography_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpage',
            name='bibliography',
        ),
    ]
