# Generated by Django 3.2.10 on 2022-02-06 23:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0069_rename_bibliography_test_documentpage_bibliography'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='transcription_test',
            field=wagtail.fields.StreamField([('transcription_text', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'underline', 'strikethrough', 'small', 'red', 'blue', 'green', 'blockquote', 'blockindent', 'doubleindent', 'center', 'superscript', 'subscript', 'ul', 'image', 'link', 'hr', 'embed'])), ('source_image', wagtail.images.blocks.ImageChooserBlock(help_text='Source image'))], blank=True, null=True),
        ),
    ]
