# Generated by Django 3.2.10 on 2022-02-07 00:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0070_documentpage_transcription_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='transcription_test',
            field=wagtail.core.fields.StreamField([('transcription_row', wagtail.core.blocks.StructBlock([('transcription_text', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'underline', 'strikethrough', 'small', 'red', 'blue', 'green', 'blockquote', 'blockindent', 'doubleindent', 'center', 'superscript', 'subscript', 'ul', 'image', 'link', 'hr', 'embed'])), ('source_image', wagtail.images.blocks.ImageChooserBlock(help_text='Source image'))], icon='edit'))], blank=True, null=True),
        ),
    ]
