# Generated by Django 3.2.10 on 2022-02-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0073_alter_documentpage_transcription_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpage',
            name='source_image',
        ),
        migrations.RemoveField(
            model_name='documentpage',
            name='transcription',
        ),
    ]
