# Generated by Django 3.2.10 on 2022-02-07 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0074_auto_20220207_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentpage',
            old_name='transcription_test',
            new_name='transcription',
        ),
    ]
