# Generated by Django 3.2.10 on 2022-03-08 01:26

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0078_alter_documentpage_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='source',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
