# Generated by Django 3.2.10 on 2022-03-12 22:45

from django.db import migrations
import wagtail.contrib.typed_table_block.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0080_auto_20220312_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='notes',
            field=wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'bold', 'italic', 'underline', 'strikethrough', 'small', 'red', 'blue', 'green', 'blockquote', 'blockindent', 'doubleindent', 'superscript', 'subscript', 'ul', 'image', 'link', 'hr', 'embed'], template='streams/richtext_block.html')), ('table', wagtail.contrib.typed_table_block.blocks.TypedTableBlock([('text', wagtail.blocks.CharBlock(required=False)), ('numeric', wagtail.blocks.FloatBlock(required=False)), ('rich_text', wagtail.blocks.RichTextBlock(features=['italic', 'bold', 'strikethrough', 'superscript', 'subscript', 'red', 'blue', 'link', 'h2'], required=False))])), ('images', wagtail.blocks.StructBlock([('images', wagtail.blocks.RichTextBlock(features=['image'])), ('caption', wagtail.blocks.RichTextBlock(features=['italic', 'bold', 'strikethrough', 'link'], form_classname='centered', required=False))], icon='image', label='Images with Caption'))], blank=True, null=True),
        ),
    ]
