# Generated by Django 3.2.10 on 2022-07-23 23:50

from django.db import migrations
import wagtail.contrib.typed_table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0083_alter_documentpage_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='notes',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'bold', 'italic', 'underline', 'strikethrough', 'small', 'red', 'blue', 'green', 'blockquote', 'blockindent', 'doubleindent', 'superscript', 'subscript', 'ul', 'image', 'link', 'hr', 'embed'], template='streams/richtext_block.html')), ('images', wagtail.core.blocks.StructBlock([('images', wagtail.core.blocks.RichTextBlock(features=['image'])), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'strikethrough', 'link'], form_classname='centered', required=False))], icon='image', label='Images with Caption')), ('side_by_side', wagtail.core.blocks.StructBlock([('transcription_text', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'bold', 'italic', 'underline', 'strikethrough', 'small', 'red', 'blue', 'green', 'blockquote', 'blockindent', 'doubleindent', 'superscript', 'subscript', 'ul', 'image', 'link', 'hr', 'embed'])), ('source_image', wagtail.images.blocks.ImageChooserBlock(help_text='Source image', required=False))], icon='edit', label='Transcription with Source')), ('table', wagtail.contrib.typed_table_block.blocks.TypedTableBlock([('text', wagtail.core.blocks.CharBlock(required=False)), ('numeric', wagtail.core.blocks.FloatBlock(required=False)), ('rich_text', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'strikethrough', 'superscript', 'subscript', 'red', 'blue', 'link', 'h2'], required=False))])), ('heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'strikethrough', 'link'], form_classname='full-title')), ('link_id', wagtail.core.blocks.CharBlock(help_text='For making hyperlinks to this heading'))], icon='title'))], blank=True, null=True),
        ),
    ]
