# Generated by Django 3.2.7 on 2021-09-01 23:20

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_page_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
