# Generated by Django 3.2.7 on 2021-09-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='lead',
            field=models.CharField(blank=True, help_text='Lead paragraph text', max_length=100),
        ),
    ]
