# Generated by Django 3.2.7 on 2021-09-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='lead',
        ),
    ]
